services:
  - type: web
    name: africatradeawards-frontend
    env: static
    buildCommand: npm install && npm run sass:build && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 18.x
